name: singularity-deploy

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Apptainer
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2
      - name: Build the Apptainer container
        run:  apptainer build -f Gistic2.sif ./Gistic2.def
      - name: upload final image to release
        uses: softprops/action-gh-release@v2
        with:
          files: Gistic2.sif
