name: test auto tag

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: compute new tag
        id: compute_tag
        uses: craig-day/compute-tag@v18
        with:
          github_token: ${{ github.token }}
          version_type: patch
      - name: final check
        run: echo ${{ steps.compute_tag.outputs.next_tag }}
